# Generated by Django 4.2.3 on 2024-07-07 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecourse', '0004_alter_choice_id_alter_course_id_alter_enrollment_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learner',
            name='social_link',
            field=models.URLField(null=True),
        ),
    ]
